apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: my-cluster
          image: gcr.io/terraform-gke-openvino/text-gen-amd:base
          ports:
            - containerPort: 80